apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      nodeSelector:
        zookeeper: "true"
      volumes:
      - name: zookeeperdata
        hostPath:
          path: "/mnt/data/zookeeper"
      containers:
      - name: zookeeper
        volumeMounts:
          - name: zookeeperdata
            mountPath: "/data/"
        image: zookeeper
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 200m
            memory: "1024Mi"
        ports:
        - name: zookeeper
          containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: NodePort
  ports:
    - name: zookeeper
      port: 2181
      nodePort: 32181
  selector:
    app: zookeeper