apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 1
  template:
      metadata:
        labels:
          app: kafka
      spec:
        nodeSelector:
          kafka: "true"
        terminationGracePeriodSeconds: 10
        volumes:
          - name: kafka
            hostPath:
              path: "/mnt/data/kafka"
        containers:
        - name: kafka
          image: wurstmeister/kafka:0.11.0.1
          env:
            - name: JAVA_OPTIONS
              value: "-Xmx1500m"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: KAFKA_ADVERTISED_PORT
              value: "30092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "39.107.126.136"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 39.106.153.134:32181
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 500m
              memory: "2048Mi"
            requests:
              memory: "1024Mi"
              cpu: 100m
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka
              mountPath: "/kafka/"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: NodePort
  ports:
    - name: kafka
      port: 9092
      nodePort: 30092
  selector:
    app: kafka