apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        mongodb: "true"
      volumes:
      - name: mongodb
        hostPath:
          path: "/mnt/data/mongodb"
      containers:
      - name: mongodb
        volumeMounts:
          - name: mongodb
            mountPath: "/data/db"
        image: mongo
        resources:
          limits:
            cpu: 200m
            memory: "500Mi"
          requests:
            memory: "200Mi"
            cpu: 100m
        ports:
        - name: mongodb
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    nodePort: 30017
  selector:
    app: mongodb